# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'
# Sets FOO to be "some value" in the script and the next ones
# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: localversion=`echo "console.log(require('./package.json').version);" | node`      
#     #npmversion=`echo npm view nodets-ms-core version`
# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: echo $localversion
# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: echo "##vso[task.setvariable variable=version]$localversion"
# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: echo $(version)

- script: | 
    npmVersionString=$(node -p "require('./package.json').version")
    echo "##vso[task.setvariable variable=localVersion;]$npmVersionString"
  displayName: 'Getting local version'

- script: | 
    npmRemoteVersion=$(npm view nodets-ms-core version) 
    echo "##vso[task.setvariable variable=remoteVersion;]$npmRemoteVersion"
  displayName: 'Getting remote version'

- script: 
   echo "Local version $(localVersion) and remote version $(remoteVersion)"
  displayName: 'Printing local and remote versions.'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
- task: Npm@1
  condition: gt(variables['localVersion'],variables['remoteVersion'])
  inputs:
    command: 'publish'
    publishEndpoint: 'NPM Publish Account'
